# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b08f7b62a00d8409d9563f10b2b2c5e2e4bee61476e568a6353f7ccd7eeb602572e1c392a76be612f94411cdf140eeb209cd2fc1e143dd89c950af0ec8ec14a5

test:
  secret_key_base: b4916a55e4b04667ab458f2d478c9ca18c63d6258781307da217734116fab0992eb1ecd5c576a62dc1fbfa99ab14c2a39b16b84d9e6fa6151252655c806446b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
